language: python - "3.6"

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended

install:
  - pip install --user sphinx sphinx-rtd-theme travis-sphinx

script:
  travis-sphinx build

after_success:
  travis-sphinx deploy
